-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKnwHaxgeIsq5+Pfa
PaWSmu0AWkaAkoHnqcWcpz12oyOgCgYIKoZIzj0DAQehRANCAAQaQocK4ej6Pfbi
HkffA/79jVTfrLvwpW2lnnlV/R+flbZ5szQNq5GQty39LDcQrchitWhlVUORw4bu
3ABca4nI
-----END PRIVATE KEY-----